# Generated by Django 4.1.7 on 2023-03-02 19:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post", managers=[("object", django.db.models.manager.Manager()),],
        ),
    ]
