# Generated by Django 4.1.7 on 2023-03-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(name="post", managers=[],),
    ]
